[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"


[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[constraint]]
    name="github.com/nalej/derrors"
    version="v2.0.0"

[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="v1.1.0"

[[constraint]]
    name="github.com/nalej/grpc-organization-go"
    version="v0.0.8"

[[constraint]]
    name="github.com/nalej/grpc-infrastructure-go"
    version="v0.0.8"

[[constraint]]
    name="github.com/nalej/grpc-authx-go"
    version="=v0.0.16"

[[constraint]]
    name="github.com/nalej/authx"
    branch="master"

[[constraint]]
    name="github.com/nalej/grpc-user-go"
    version="v0.0.5"

[[constraint]]
    name="github.com/nalej/grpc-user-manager-go"
    version="v0.0.6"

[[constraint]]
    name="github.com/nalej/grpc-role-go"
    version="v0.0.4"

[[constraint]]
    name="github.com/nalej/grpc-public-api-go"
    version="v0.0.6"

[[constraint]]
    name="github.com/nalej/grpc-login-api-go"
    version="v0.0.3"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="v0.0.7"

[[constraint]]
    name="github.com/grpc-ecosystem/grpc-gateway"
    version="v1.5.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

