[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"


[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[constraint]]
    name="github.com/nalej/derrors"
    version="v2.0.0"

[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="v1.2.0"

[[constraint]]
    name="github.com/nalej/grpc-installer-go"
    version="v0.0.29"

[[constraint]]
    name="github.com/nalej/grpc-organization-go"
    version="v0.0.28"

[[constraint]]
    name="github.com/nalej/grpc-infrastructure-go"
    version="v0.0.32"

[[constraint]]
    name="github.com/nalej/grpc-application-manager-go"
    version="v0.0.27"

[[constraint]]
    name="github.com/nalej/grpc-application-go"
    version="v0.0.47"

[[constraint]]
    name="github.com/nalej/grpc-conductor-go"
    version="v0.0.66"

[[constraint]]
    name="github.com/nalej/grpc-authx-go"
    version="v0.0.41"

[[constraint]]
    name="github.com/nalej/authx"
    branch="master"

[[constraint]]
    name="github.com/nalej/grpc-user-go"
    version="v0.0.29"

[[constraint]]
    name="github.com/nalej/grpc-user-manager-go"
    version="v0.0.27"

[[constraint]]
    name="github.com/nalej/grpc-device-manager-go"
    version="v0.0.2"

[[constraint]]
    name="github.com/nalej/grpc-public-api-go"
    version="v0.0.43"

[[constraint]]
    name="github.com/nalej/grpc-login-api-go"
    version="v0.0.17"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="v0.0.30"

[[constraint]]
    name="github.com/grpc-ecosystem/grpc-gateway"
    version="=v1.5.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/nalej/grpc-unified-logging-go"
  version = "v0.0.1"
 
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/araddon/dateparse"
  revision = "21df004e09ca46e07ce99bbba1e8c2422ba4ecf9"
