###
# Public API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: public-api
  name: public-api
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: public-api
  template:
    metadata:
      labels:
        cluster: management
        component: public-api
    spec:
      volumes:
      - name: authx-config
        configMap:
          name: public-api-authx-config
      containers:
      - name: public-api
        image: nalejregistry.azurecr.io/nalej/public-api:VERSION
        env:
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: authx-secret
                key: secret
        volumeMounts:
          - name: authx-config
            mountPath: "/nalej/config"
            readOnly: true
        # TODO link secret, file, etc.
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--infrastructureManagerAddress=infrastructure-manager.nalej:8081"
        - "--applicationsManagerAddress=application-manager.nalej:8910"
        - "--userManagerAddress=user-manager.nalej:8920"
        - "--deviceManagerAddress=device-manager.nalej:6010"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
