kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: public-api
  name: public-api-authx-config
  namespace: __NPH_NAMESPACE
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/public_api.Clusters/Install":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/ProvisionAndInstall":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/Scale":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/Info":{"should":["ORG", "RESOURCES"]},
       "/public_api.Clusters/List":{"should":["ORG", "RESOURCES"]},
       "/public_api.Clusters/Monitor":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/Update":{"should":["ORG", "RESOURCES"]},
       "/public_api.Clusters/Cordon":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/Uncordon":{"must":["RESOURCES_MNGT"]},
       "/public_api.Clusters/Drain":{"must":["RESOURCES_MNGT"]},
       "/public_api.Nodes/List":{"should":["ORG", "RESOURCES"]},
       "/public_api.Nodes/UpdateNode":{"must":["RESOURCES_MNGT"]},
       "/public_api.Organizations/Info":{"should":["ORG", "RESOURCES", "APPS"]},
       "/public_api.Resources/Summary":{"should":["ORG", "RESOURCES"]},
       "/public_api.Roles/List":{"must":["ORG"]},
       "/public_api.Roles/ListInternal":{"must":["ORG_MNGT"]},
       "/public_api.Roles/AssignRole":{"must":["ORG_MNGT"]},
       "/public_api.Users/Add":{"must":["ORG_MNGT"]},
       "/public_api.Users/Info":{"should":["ORG", "PROFILE", "ORG_MNGT"]},
       "/public_api.Users/List":{"should":["ORG", "ORG_MNGT"]},
       "/public_api.Users/Delete":{"must":["ORG_MNGT"]},
       "/public_api.Users/ChangePassword":{"should":["ORG", "PROFILE", "ORG_MNGT"]},
       "/public_api.Users/Update":{"should":["ORG", "PROFILE", "ORG_MNGT"]},
       "/public_api.Applications/AddAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListAppDescriptors":{"should":["ORG", "APPS"]},
       "/public_api.Applications/GetAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/UpdateAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/DeleteAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListDescriptorAppParameters":{"should":["ORG", "APPS"]},
       "/public_api.Applications/Deploy":{"should":["ORG", "APPS"]},
       "/public_api.Applications/Undeploy":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListAppInstances":{"should":["ORG", "APPS"]},
       "/public_api.Applications/GetAppInstance":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListInstanceParameters":{"should":["ORG", "APPS"]},
       "/public_api.ApplicationNetwork/AddConnection": {"should":["ORG", "APPS"]},
       "/public_api.ApplicationNetwork/RemoveConnection": {"should":["ORG", "APPS"]},
       "/public_api.ApplicationNetwork/ListConnections": {"should":["ORG", "APPS"]},
       "/public_api.ApplicationNetwork/ListAvailableInstanceInbounds": {"should":["ORG", "APPS"]},
       "/public_api.ApplicationNetwork/ListAvailableInstanceOutbounds": {"should":["ORG", "APPS"]},
       "/public_api.UnifiedLogging/Search":{"should":["ORG", "APPS"]},
       "/public_api.Devices/AddDeviceGroup":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/UpdateDeviceGroup":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/RemoveDeviceGroup":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/ListDeviceGroups":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/ListDevices":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/AddLabelToDevice":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/RemoveLabelFromDevice":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/UpdateDevice":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/RemoveDevice":{"should":["ORG", "DEVMNGR"]},
       "/public_api.Devices/GetDevice":{"should":["ORG", "DEVMNGR"]},
       "/public_api.EdgeControllers/CreateEICToken":{"must":["RESOURCES_MNGT"]},
       "/public_api.EdgeControllers/UnlinkEIC":{"must":["RESOURCES_MNGT"]},
       "/public_api.EdgeControllers/UpdateGeolocation":{"must":["RESOURCES_MNGT"]},
       "/public_api.EdgeControllers/InstallAgent":{"must":["RESOURCES_MNGT"]},
       "/public_api.Inventory/List":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/Summary":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/GetControllerExtendedInfo":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/GetAssetInfo":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/GetDeviceInfo":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/UpdateDeviceLocation":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/AddLabelToAsset":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/RemoveLabelFromAsset":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/UpdateEdgeController":{"must":["RESOURCES_MNGT"]},
       "/public_api.Inventory/AddLabelToDevice":{"should":["ORG", "RESOURCES"]},
       "/public_api.Inventory/RemoveLabelFromDevice":{"should":["ORG", "RESOURCES"]},
       "/public_api.InventoryMonitoring/ListMetrics":{"should":["ORG", "RESOURCES"]},
       "/public_api.InventoryMonitoring/QueryMetrics":{"should":["ORG", "RESOURCES"]},
       "/public_api.InventoryMonitoring/ConfigureMetrics":{"should":["ORG", "RESOURCES"]},
       "/public_api.Monitoring/GetClusterStats":{"should":["ORG", "RESOURCES"]},
       "/public_api.Monitoring/GetClusterSummary":{"should":["ORG", "RESOURCES"]},
       "/public_api.Agent/CreateAgentJoinToken":{"must":["RESOURCES_MNGT"]},
       "/public_api.Agent/ActivateMonitoring":{"must":["RESOURCES_MNGT"]},
       "/public_api.Agent/UninstallAgent":{"must":["RESOURCES_MNGT"]},
       "/public_api.Provision/ProvisionCluster":{"must":["RESOURCES_MNGT"]},
       "/public_api.Provision/CheckProgress":{"must":["RESOURCES_MNGT"]},
       "/public_api.Provision/RemoveProvision":{"must":["RESOURCES_MNGT"]}
     }
    }
