kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: public-api
  name: public-api-authx-config
  namespace: nalej
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/public_api.Clusters/Install":{"should":["ORG", "RESOURCES"]},
       "/public_api.Clusters/List":{"should":["ORG", "RESOURCES"]},
       "/public_api.Clusters/Update":{"should":["ORG", "RESOURCES"]},
       "/public_api.Nodes/ClusterNodes":{"should":["ORG", "RESOURCES"]},
       "/public_api.Organizations/Info":{"must":["ORG"]},
       "/public_api.Resources/Summary":{"should":["ORG", "RESOURCES"]},
       "/public_api.Roles/List":{"must":["ORG"]},
       "/public_api.Users/Add":{"must":["ORG"]},
       "/public_api.Users/Info":{"should":["ORG", "PROFILE"]},
       "/public_api.Users/List":{"must":["ORG"]},
       "/public_api.Users/Delete":{"must":["ORG"]},
       "/public_api.Users/ResetPassword":{"should":["ORG", "PROFILE"]},
       "/public_api.Users/Update":{"should":["ORG", "PROFILE"]},
       "/public_api.Applications/AddAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListAppDescriptors":{"should":["ORG", "APPS"]},
       "/public_api.Applications/GetAppDescriptor":{"should":["ORG", "APPS"]},
       "/public_api.Applications/Deploy":{"should":["ORG", "APPS"]},
       "/public_api.Applications/Undeploy":{"should":["ORG", "APPS"]},
       "/public_api.Applications/ListAppInstances":{"should":["ORG", "APPS"]},
       "/public_api.Applications/GetAppInstance":{"should":["ORG", "APPS"]}
     }
    }
